spring:
  docker:
    compose:
      enabled: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/goods_agr
  jpa:
    properties.hibernate:
      ddl-auto: create-drop
      format_sql: true
    open-in-view: false
  mvc:
    format:
      date: iso